FROM node:14 as builder

WORKDIR /tmp/build
COPY . /tmp/build

RUN npm install
RUN npm i -g @zeit/ncc
RUN ncc build src/server.ts

FROM node:14-alpine

WORKDIR /svc/proxy
EXPOSE 12321

COPY --from=builder /tmp/build/dist/index.js /svc/proxy/index.js

CMD node index.js